Lock in pinned Ruby support for EYAML

diff --git a/.github/workflows/python-publish-to-test-pypi.yml b/.github/workflows/python-publish-to-test-pypi.yml
--- a/.github/workflows/python-publish-to-test-pypi.yml
+++ b/.github/workflows/python-publish-to-test-pypi.yml
@@ -17,17 +17,8 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        include:
-          - python-version: '3.10'
-            test-tools-constraints: requirements/test-tools/py310.txt
-          - python-version: '3.11'
-            test-tools-constraints: requirements/test-tools/py311.txt
-          - python-version: '3.12'
-            test-tools-constraints: requirements/test-tools/py312.txt
-          - python-version: '3.13'
-            test-tools-constraints: requirements/test-tools/py313.txt
-          - python-version: '3.14'
-            test-tools-constraints: requirements/test-tools/py314.txt
+        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
+        ruby-version: ['3.4']
 
     steps:
     - uses: actions/checkout@v4
@@ -35,16 +26,28 @@ jobs:
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Set Environment Variables
+    - name: Set up Ruby ${{ matrix.ruby-version }}
+      uses: ruby/setup-ruby@v1
+      with:
+        ruby-version: ${{ matrix.ruby-version }}
+    - name: Install EYAML
       run: |
-        echo "${HOME}/.local/share/gem/ruby/3.0.0/bin" >> $GITHUB_PATH
-    - name: Install dependencies
+        ruby_constraints_file="requirements/test-tools/ruby-${{ matrix.ruby-version }}.txt"
+        if ! [ -f "$ruby_constraints_file" ]; then
+          echo "ERROR: Unsupported Ruby branch for CI: ${{ matrix.ruby-version }}" >&2
+          echo "Expected dependency file not found: $ruby_constraints_file" >&2
+          exit 1
+        fi
+        gem install --user-install --no-document -g "$ruby_constraints_file" --no-lock
+        ruby_gem_user_bin="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"
+        echo "$ruby_gem_user_bin" >> "$GITHUB_PATH"
+        "$ruby_gem_user_bin/eyaml" --version
+    - name: Install Python dependencies
       run: |
-        gem install --user-install hiera-eyaml
         python -m pip install --upgrade pip
         python -m pip install --upgrade setuptools
         python -m pip install --upgrade wheel
-        python -m pip install -r ${{ matrix.test-tools-constraints }}
+        python -m pip install -r requirements/test-tools/python-${{ matrix.python-version }}.txt
         python -m pip install --editable .
     - name: Validate Compliance with pydocstyle
       run: |
